# Generated by Django 4.0.1 on 2022-01-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('carts', models.ManyToManyField(related_name='carts', through='orders.Cart', to='products.Product')),
                ('reviews', models.ManyToManyField(related_name='reviews', through='services.Review', to='products.Product')),
                ('wishlists', models.ManyToManyField(related_name='wishlists', through='orders.Wishlist', to='products.Product')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
