# Generated by Django 4.0.1 on 2022-01-25 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcomponent_component_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='carts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='user',
            name='wishlists',
        ),
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(related_name='user_cart_product', through='orders.Cart', to='products.Product'),
        ),
        migrations.AddField(
            model_name='user',
            name='review',
            field=models.ManyToManyField(related_name='user_review_product', through='services.Review', to='products.Product'),
        ),
        migrations.AddField(
            model_name='user',
            name='wishlist',
            field=models.ManyToManyField(related_name='user_wishlist_product', through='orders.Wishlist', to='products.Product'),
        ),
    ]
