# Generated by Django 4.0.1 on 2022-01-25 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='services.shop'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='users.user'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='reservation',
            field=models.ManyToManyField(related_name='reservation', through='services.Reservation', to='users.User'),
        ),
    ]
