# Generated by Django 4.0.1 on 2022-01-25 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productcomponent_component_and_more'),
        ('users', '0002_remove_user_carts_remove_user_reviews_and_more'),
        ('services', '0002_alter_reservation_shop_alter_reservation_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='order_item',
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product'),
        ),
        migrations.AlterField(
            model_name='review',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.user'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='reservation',
            field=models.ManyToManyField(related_name='user_reservation_shop', through='services.Reservation', to='users.User'),
        ),
    ]
