# Generated by Django 4.0.1 on 2022-01-27 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
